apiVersion: v1
kind: Service
metadata:
  name: sample-externalip
spec:
  type: ClusterIP
  externalIPs:
    - 10.146.0.3
    - 10.146.0.2
    - 10.146.0.4
  selector:
    app: sample-pod
  ports:
  - port: 8080
    targetPort: 80
    name: "http-port"
    protocol: "TCP"