apiVersion: v1
kind: Service
metadata:
  name: sample-lb
spec:
  type: LoadBalancer
  selector:
    app: sample-pod
  ports:
  - port: 8080
    targetPort: 80
    protocol: "TCP"
    name: "http-port"
    nodePort: 30082
